### ISSUE TITLE
Export with SSH-Connector doesn't work on pollers.

### ISSUE THREAD

**Issue by itsul** [centreon/centreon-connectors#7]
Centreon Version 2.8.17
Centreon Engine 1.8.1
Centreon Connector 1.1.3

We have a working environment with ssh-connectors on the central instance. When we switch a host to a poller, we get the following error:

![error_connector](https://user-images.githubusercontent.com/12328177/36434825-421e74d4-1660-11e8-8dbf-398c7e7e6e81.png)

... quite similar as mentioned [here:](https://github.com/centreon/centreon/issues/4272)

For testing purposes we'd turn off debugging, exported and added the following lines to the connectors.cfg on the target poller:

define connector {
    connector_name                 SSH Connector
    connector_line                 /usr/lib64/centreon-connector/centreon_connector_ssh
}
define connector {
    connector_name                 Perl Connector
    connector_line                 /usr/lib64/centreon-connector/centreon_connector_perl
}

After we restarted the engine, it worked fine.

The missing lines doesn't show up in the filesGeneration/engine/#/connectors.cfg on the central-web instance.

Any ideas?

**Comment by ganoze** [comment]
Thank you for your feedback. However this does not seem to be an issue with Centreon Connectors (nor Centreon Engine). This is more likely caused by Centreon Web's configuration generation subsystem.

I suggest that you open another issue in [Centreon Web project](https://github.com/centreon/centreon) with the details that you provided here and a precise reproductible scenario.
